name: Scala SBT CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: sbtscala/scala-sbt:openjdk-8u342_1.8.0_2.13.10
  
    steps:
    - name: Clone the Repository
      uses: actions/checkout@v3
    - name: Run tests
      run: sbt test
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
